#!/bin/bash -l

#SBATCH -A project_number
#SBATCH -p shared
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --ntasks-per-node 1
#SBATCH --cpus-per-task 2
#SBATCH -t 10:00:00
#SBATCH -J run_test
#SBATCH -e err/%x-%j.error
#SBATCH -o err/%x-%j.out

#use dardel.config to run on SLURM
nextflow run main.nf -profile apptainer,conda -c test.config,dardel.config -resume -with-trace
